server:
  port: ${PORT:8062}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
          
spring:
  boot:
     admin:
        instance:
           metadata:
              tags:
                 environment: Test
  jackson:
    serialization:
      INDENT_OUTPUT: true           
  zipkin:
    base-url: http://localhost:9411/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: employee-service
        uri: lb://employee-service
        predicates:
        - Path=/employee/**
        filters:
        - RewritePath=/employee/(?<path>.*), /$\{path}
      - id: department-service
        uri: lb://department-service
        predicates:
        - Path=/department/**
        filters:
        - RewritePath=/department/(?<path>.*), /$\{path}
      - id: organization-service
        uri: lb://organization-service
        predicates:
        - Path=/organization/**
        filters:
        - RewritePath=/organization/(?<path>.*), /$\{path}

logging:
  file: "D:/New_Projects/DevOps/DockerPOC/logs/gateway-services.log"
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx" 

management:
   security:
      enabled: false
   endpoints:
      web:
         exposure:
            include: "*"
   endpoint:
    health:
      show-details: ALWAYS
      
info.tags.environment: Test Environment